### PR TITLE
same treatment to cytrus-re's site

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Context: https://github.com/terrific-tea/terrific-tea.github.io/pull/12

**Comment by Rexogamer** [comment]
I think we wanted to set up the global header but sure

**Comment by ghost** [comment]
btw why is there LGTM on a website? Isn't that quite useless? Even more so since we don't use js here

**Comment by ghost** [comment]
Hmm, tts' site does it another way that isn't like this. I tried to make it work earlier but then I didn't have time to do so

**Comment by Rexogamer** [comment]
> btw why is there LGTM on a website? Isn't that quite useless? Even more so since we don't use js here

I think LGTM was somehow set up org wide?

> Hmm, tts' site does it another way that isn't like this. I tried to make it work earlier but then I didn't have time to do so

It'll be useful to set up

**Comment by ghost** [comment]
The method I tried here was broken. It didn't work.

**Comment by ghost** [comment]
I mean, if you want to have broken code, I can revert the change.

**Comment by Rexogamer** [comment]
Oh no, it's fine. We'll get the header set up in a separate PR.

**Comment by ghost** [comment]
Alright.

**Pull request merged**
